/**
 * Round 2026-09-25 (locale-aware PWA launch, per Hamid's brief). One source
 * of truth for the locale-keyed web app manifest data, plus the mapping
 * from locale to the manifest URL that locale's pages must link.
 *
 * WHY THIS EXISTS: the manifest was a single `public/manifest.webmanifest`
 * with `start_url: "/"`, so every install — whichever language the patient
 * was reading — launched the Persian homepage. Each locale now has its own
 * manifest carrying the correct `start_url` and locale-appropriate
 * `name`/`short_name`/`description`/`lang`/`dir`, so an install from `/en`
 * launches at `/en` and one from `/ar` at `/ar`.
 *
 * TWO SERVING PATHS, deliberately (see each one's own note):
 * - `fa` → `/manifest.webmanifest`, the existing static
 *   `public/manifest.webmanifest`. Persian's canonical public URLs are
 *   bare-root, and a static file is what already serves that exact path in
 *   production; the middleware matcher excludes any path containing a dot
 *   (`/((?!_next|.*\..*).*)`), so this file is served directly and is never
 *   rewritten or redirected.
 * - `en`/`ar` → `/[locale]/manifest.webmanifest`, generated by
 *   `src/app/[locale]/manifest.ts` (Next's `manifest.ts` metadata-file
 *   convention), which resolves through `buildPwaManifest` below.
 *
 * CONSEQUENCE TO KEEP IN MIND: the Persian values below are mirrored by the
 * static `public/manifest.webmanifest` file, which cannot import this
 * module. If Persian manifest data ever changes, both places change
 * together. Nothing else about that file changed — its `start_url`, `scope`,
 * `id`, `display`, colors and icons are exactly as they were.
 */
import type { MetadataRoute } from "next";

import { SUPPORTED_LOCALES, type Locale } from "@/i18n/locales";

/**
 * The manifest each locale's pages link. Persian's is the bare path
 * (`metadataBase` resolves it to the production origin) — its English and
 * Arabic equivalents are the two real public locale roots.
 */
export const PWA_MANIFEST_PATH: Record<Locale, string> = {
  fa: "/manifest.webmanifest",
  en: "/en/manifest.webmanifest",
  ar: "/ar/manifest.webmanifest",
};

/**
 * Persian's manifest is the pre-existing static `public/manifest.webmanifest`
 * served at the bare `/manifest.webmanifest` (the middleware matcher excludes
 * dotted paths, so that file is served directly and is neither rewritten nor
 * redirected). The other locales are generated from this module — see
 * `app/[locale]/manifest.webmanifest/route.ts`.
 *
 * This distinction is what keeps the change free of new public `/fa/…` URLs:
 * `fa` is deliberately excluded from the generated set, so
 * `/fa/manifest.webmanifest` continues not to exist.
 */
export const STATIC_MANIFEST_LOCALE: Locale = "fa";

export const GENERATED_MANIFEST_LOCALES: Locale[] = SUPPORTED_LOCALES.filter(
  (locale) => locale !== STATIC_MANIFEST_LOCALE,
);

/**
 * The installed app's launch URL. Persian's canonical public root is bare
 * `/`, never `/fa` (see `AGENTS.md` routing rules) — so this is the same
 * set of URLs `localeHref(locale)` produces, kept literal here because a
 * manifest `start_url` is a real install-time URL, not a nav link.
 */
const START_URL: Record<Locale, string> = {
  fa: "/",
  en: "/en",
  ar: "/ar",
};

/**
 * Localized app identity. Persian mirrors `public/manifest.webmanifest`
 * exactly (see the file doc-comment); the wording follows the clinic-name
 * and doctor-name pairs already established for each locale in
 * `core/structured-data.ts` (`CLINIC_NAME`/`DOCTOR_NAME`) and each
 * dictionary's header, so the installed app's label matches the name the
 * site uses everywhere else rather than introducing a new variant.
 */
const APP_NAME: Record<Locale, string> = {
  fa: "کلینیک دکتر علیرضا صدیقی",
  en: "Dr. Alireza Sadighi Aesthetic Clinic",
  ar: "عيادة الدكتور عليرضا صديقي للتجميل",
};

/** Shown under the home-screen icon, so it has to stay short. */
const APP_SHORT_NAME: Record<Locale, string> = {
  fa: "دکتر صدیقی",
  en: "Dr. Sadighi",
  ar: "د. صديقي",
};

const APP_DESCRIPTION: Record<Locale, string> = {
  fa: "کلینیک دکتر علیرضا صدیقی — جراحی تخصصی فک و صورت و زیبایی، تهران و تبریز.",
  en: "Dr. Alireza Sadighi Aesthetic Clinic — specialized maxillofacial and cosmetic surgery, Tehran and Tabriz.",
  ar: "عيادة الدكتور عليرضا صديقي للتجميل — جراحة متخصصة للفك والوجه والتجميل، طهران وتبريز.",
};

export const PWA_LANG: Record<Locale, string> = { fa: "fa", en: "en", ar: "ar" };
export const PWA_DIR: Record<Locale, "rtl" | "ltr"> = { fa: "rtl", en: "ltr", ar: "rtl" };

/** Existing branded assets — no placeholder icons were generated. */
const PWA_ICONS: MetadataRoute.Manifest["icons"] = [
  { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
];

/** The iOS home-screen label, from the same localized short name. */
export function pwaShortName(locale: Locale): string {
  return APP_SHORT_NAME[locale];
}

/**
 * Builds one locale's manifest. `id` and `scope` stay `/` for every locale
 * on purpose: this is ONE clinic app, so installing it in another language
 * must not create a second icon on the device — only the launch URL and the
 * display language change. `start_url` (`/en`, `/ar`) is inside `scope` (`/`),
 * which is what installability requires.
 */
export function buildPwaManifest(locale: Locale): MetadataRoute.Manifest {
  return {
    name: APP_NAME[locale],
    short_name: APP_SHORT_NAME[locale],
    description: APP_DESCRIPTION[locale],
    start_url: START_URL[locale],
    scope: "/",
    id: "/",
    display: "standalone",
    orientation: "portrait-primary",
    lang: PWA_LANG[locale],
    dir: PWA_DIR[locale],
    background_color: "#fcfbf4",
    theme_color: "#0f172a",
    icons: PWA_ICONS,
  };
}
